<a href="https://colab.research.google.com/github/ali-s3/CSS-Responsive/blob/main/Copy_of_LISA_Project_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Our goal is to analyze:
1. Which companies perform better when the average ROE of 21.17% is compared to the ROE of the top 100? Which are the worst? What is the correlation between these companies' ROE and the market cap/current ratio?

2. What is the correlation between market capitalization and total debt? Is it true that a corporation with a large market cap also has the most debt? Or, the greater a company's market capitalization, the lower its debt?

3. How has the stock market performed over a specific time period? Is there mmore or less volatility in a company's stock price during the day if it is large-company?

The process to achieve our goal is composed by :

1. Data Cleaning
2. Processing and scaling data
3. Dimensionality reduction
4. Cluster analysis
5. Key insights and findings

#Lab of Information Systems and Analytics

The project involves applying the machine learning techniques covered in the lectures to perform a data analysis task.
The data will be sourced from Yahoo Finance and Twitter and will focus on the stock market behavior of 100 well-known stock indices, along with associated tweets.

Boschetti Vittoria 888699 - Carnio Marta 891943 - Fiorasi Elena 892077 - Magrin Giulia 888538

In [ ]:
# we import the files in the notebook
import pandas as pd
stocks = pd.read_csv("top100.csv")
stocks

,Unnamed: 0.7,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Stock Name,Date,Open,Close,High,Low,Volume
0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,AAPL,2022-01-10 05:00:00,169.0800,172.19,172.5000,168.1700,106754551.0
1,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,AAPL,2022-01-11 05:00:00,172.3200,175.08,175.1800,170.8200,76138312.0
2,2,2.0,2.0,2.0,2.0,2.0,2.0,2.0,AAPL,2022-01-12 05:00:00,176.1200,175.53,177.1800,174.8200,74805173.0
3,3,3.0,3.0,3.0,3.0,3.0,3.0,3.0,AAPL,2022-01-13 05:00:00,175.7800,172.19,176.6200,171.7900,84405760.0
4,4,4.0,4.0,4.0,4.0,4.0,4.0,4.0,AAPL,2022-01-14 05:00:00,171.3400,173.07,173.7800,171.0900,80440778.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24844,246,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VYM,2023-01-03 05:00:00,108.5200,108.02,108.8000,107.2000,2377721.0
24845,247,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VYM,2023-01-04 05:00:00,108.3200,108.94,109.5000,108.0300,7427816.0
24846,248,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VYM,2023-01-05 05:00:00,108.4881,108.39,108.7500,107.8209,1829917.0
24847,249,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VYM,2023-01-06 05:00:00,109.2900,110.77,111.0500,109.0900,1624080.0
24848,250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VYM,2023-01-09 05:00:00,111.1400,109.82,111.3791,109.7600,2572711.0

Some additional information about our dataframe stocks:

In [ ]:
stocks.shape

(24849, 15)

In [ ]:
stocks.info()          # obtain informaiton on columns and data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24849 entries, 0 to 24848
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0.7  24849 non-null  int64
 1   Unnamed: 0.6  12460 non-null  float64
 2   Unnamed: 0.5  7942 non-null   float64
 3   Unnamed: 0.4  4428 non-null   float64
 4   Unnamed: 0.3  1004 non-null   float64
 5   Unnamed: 0.2  753 non-null    float64
 6   Unnamed: 0.1  502 non-null    float64
 7   Unnamed: 0    251 non-null    float64
 8   Stock Name    24849 non-null  object
 9   Date          24849 non-null  object
 10  Open          24849 non-null  float64
 11  Close         24849 non-null  float64
 12  High          24849 non-null  float64
 13  Low           24849 non-null  float64
 14  Volume        24849 non-null  float64
dtypes: float64(12), int64(1), object(2)
memory usage: 2.8+ MB

In [ ]:
stock_info = pd.read_csv("top100info.csv")
stock_info

,0,AAPL,AMZN,MSFT,SNAP,HOOD,WMT,GOOG,PTON,CPRX,...,ZM,CRM,FUBO,BND,RITM,SPHD,QS,VEA,IVR,VYM
0,Market Cap (intraday),2.61T,1.05T,2.17T,16.70B,8.97B,406.50B,1.37T,3.95B,1.84B,...,21.11B,192.55B,230.66M,NaN,3.70B,NaN,3.21B,NaN,446.26M,NaN
1,Enterprise Value,2.66T,1.12T,2.13T,16.94B,-4.48B,456.80B,1.28T,5.49B,1.54B,...,15.80B,194.13B,336.37M,NaN,NaN,NaN,2.25B,NaN,NaN,NaN
2,Trailing P/E,27.96,NaN,32.40,NaN,NaN,35.32,23.45,NaN,23.17,...,211.32,916.90,NaN,NaN,4.33,NaN,NaN,NaN,1.10,NaN
3,Forward P/E,27.86,63.69,26.95,NaN,NaN,24.75,19.80,NaN,11.59,...,17.33,27.03,NaN,NaN,5.61,NaN,NaN,NaN,1.99,NaN
4,PEG Ratio (5 yr expected),2.78,2.30,2.19,NaN,NaN,4.21,1.17,NaN,NaN,...,2.69,1.35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Price/Sales (ttm),6.88,2.02,10.71,3.69,6.48,0.67,4.98,1.26,9.04,...,4.98,6.12,0.20,NaN,1.06,NaN,NaN,NaN,0.87,NaN
6,Price/Book (mrq),45.93,7.16,11.85,6.47,1.29,5.30,5.35,129.45,6.11,...,3.40,3.30,0.56,NaN,0.65,NaN,2.43,NaN,0.88,NaN
7,Enterprise Value/Revenue,6.88,2.17,10.44,3.68,-3.30,0.75,4.53,1.80,7.20,...,3.60,6.19,0.33,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Enterprise Value/EBITDA,20.81,29.10,21.58,-14.39,5.09,15.18,14.63,-2.17,14.96,...,48.20,34.40,-0.90,NaN,NaN,NaN,-6.03,NaN,NaN,NaN
9,Beta (5Y Monthly),1.30,1.25,0.92,1.20,NaN,0.49,1.09,1.95,1.16,...,-0.22,1.21,2.45,1.0,1.78,0.74,5.27,1.09,1.55,0.77
10,52-Week Change 3,-5.63%,-35.76%,-1.67%,-69.55%,-16.23%,-4.55%,-18.55%,-54.10%,104.78%,...,-39.07%,-3.49%,-78.46%,NaN,-24.79%,NaN,-58.17%,NaN,-47.61%,NaN
11,S&P500 52-Week Change 3,-7.59%,-7.59%,-7.59%,-7.59%,-7.59%,-7.59%,-7.59%,-7.59%,-7.59%,...,-7.59%,-7.59%,-7.59%,NaN,-7.59%,NaN,-7.59%,NaN,-7.59%,NaN
12,52 Week High 3,176.15,158.65,294.18,35.39,12.76,160.77,131.92,26.50,22.11,...,124.05,200.00,8.1400,NaN,11.75,NaN,18.87,NaN,20.00,NaN
13,52 Week Low 3,124.17,81.43,213.43,7.33,6.81,117.27,83.45,6.66,6.15,...,63.55,126.34,0.9600,NaN,6.86,NaN,5.11,NaN,9.60,NaN
14,50-Day Moving Average 3,154.06,98.42,265.65,10.83,9.74,142.86,98.82,12.48,15.79,...,73.00,179.13,1.7604,NaN,8.67,NaN,8.41,NaN,12.30,NaN
15,200-Day Moving Average 3,149.38,107.33,254.31,10.76,9.63,138.62,101.76,10.60,14.44,...,81.76,162.77,2.7996,NaN,8.88,NaN,8.74,NaN,13.50,NaN
16,Avg Vol (3 month) 3,65.35M,64.92M,31.87M,33.4M,7.33M,6.72M,32.5M,12.48M,2.26M,...,3.89M,8.56M,13.46M,NaN,4.68M,NaN,6.06M,NaN,970.04k,NaN
17,Avg Vol (10 day) 3,51.1M,47.52M,25.77M,22.46M,7.47M,6.78M,24.03M,6.88M,1.68M,...,2.82M,5.7M,12.51M,NaN,4.23M,NaN,3.65M,NaN,1.27M,NaN
18,Shares Outstanding 5,15.82B,10.25B,7.44B,1.33B,768.37M,2.7B,5.97B,327.13M,105.65M,...,247.17M,1B,209.7M,NaN,473.73M,NaN,360.52M,NaN,41.47M,NaN
19,Implied Shares Outstanding 6,NaN,NaN,NaN,NaN,896.05M,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Float 8,15.81B,9.24B,7.44B,969.04M,520.15M,1.42B,11.07B,304.3M,93.47M,...,223.5M,968.26M,203.97M,NaN,470.94M,NaN,276.96M,NaN,38.62M,NaN
21,% Held by Insiders 1,0.07%,9.75%,0.06%,9.39%,8.06%,48.00%,0.02%,2.28%,5.97%,...,9.34%,3.25%,4.34%,NaN,0.68%,NaN,26.03%,NaN,0.21%,NaN
22,% Held by Institutions 1,61.28%,60.46%,73.65%,52.92%,70.82%,32.88%,63.30%,88.86%,82.78%,...,66.17%,78.15%,41.49%,NaN,48.36%,NaN,39.93%,NaN,47.35%,NaN
23,"Shares Short (Mar 14, 2023) 4",107.42M,56.47M,35.91M,54.67M,35.22M,9.96M,33.46M,36M,9.78M,...,12.01M,10.74M,39.24M,NaN,4.77M,NaN,52.32M,NaN,3.69M,NaN
24,"Short Ratio (Mar 14, 2023) 4",1.75,1.01,1.3,1.72,5.31,1.36,1.12,3.85,5.81,...,2.57,1.1,2.92,NaN,1.11,NaN,7.75,NaN,2.98,NaN
25,"Short % of Float (Mar 14, 2023) 4",0.68%,0.63%,0.48%,6.60%,6.07%,0.72%,NaN,12.49%,9.99%,...,4.87%,1.11%,19.49%,NaN,1.01%,NaN,19.50%,NaN,11.81%,NaN
26,"Short % of Shares Outstanding (Mar 14, 2023) 4",0.68%,0.55%,0.48%,3.46%,3.93%,0.37%,0.26%,10.40%,9.26%,...,4.09%,1.07%,18.71%,NaN,1.01%,NaN,11.89%,NaN,8.89%,NaN
27,"Shares Short (prior month Feb 14, 2023) 4",104.34M,62.13M,36.52M,54.29M,36.33M,12.53M,28.55M,37.82M,9.74M,...,14.93M,11.02M,51.68M,NaN,14.78M,NaN,60.47M,NaN,3.9M,NaN
28,Forward Annual Dividend Rate 4,0.92,NaN,2.72,NaN,NaN,2.28,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,1.6,NaN
29,Forward Annual Dividend Yield 4,0.57%,NaN,0.94%,NaN,NaN,1.51%,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,12.82%,NaN,NaN,NaN,14.87%,NaN
30,Trailing Annual Dividend Rate 3,0.91,0.00,2.60,0.00,0.00,2.24,0.00,0.00,0.00,...,0.00,0.00,0.00,NaN,1.00,NaN,0.00,NaN,3.10,NaN
31,Trailing Annual Dividend Yield 3,0.57%,0.00%,0.92%,0.00%,0.00%,1.49%,0.00%,0.00%,0.00%,...,0.00%,0.00%,0.00%,NaN,12.63%,NaN,0.00%,NaN,30.04%,NaN
32,5 Year Average Dividend Yield 4,0.94,NaN,1.12,NaN,NaN,1.77,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,11.51,NaN,NaN,NaN,20.18,NaN
33,Payout Ratio 4,15.45%,0.00%,28.22%,0.00%,0.00%,52.46%,0.00%,0.00%,0.00%,...,0.00%,0.00%,0.00%,NaN,55.56%,NaN,0.00%,NaN,NaN,NaN
34,Dividend Date 3,"Feb 15, 2023",NaN,"Jun 07, 2023",NaN,NaN,"Jan 01, 2024",NaN,NaN,NaN,...,NaN,NaN,"Feb 27, 2019",NaN,"Apr 27, 2023",NaN,NaN,NaN,"Apr 26, 2023",NaN
35,Ex-Dividend Date 4,"Feb 09, 2023",NaN,"May 16, 2023",NaN,NaN,"May 03, 2023",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"Mar 29, 2023",NaN,NaN,NaN,"Apr 05, 2023",NaN
36,Last Split Factor 2,4:1,20:1,2:1,NaN,NaN,2:1,20:1,NaN,NaN,...,NaN,4:1,NaN,NaN,1:2,NaN,NaN,NaN,1:10,NaN
37,Last Split Date 3,"Aug 30, 2020","Jun 05, 2022","Feb 17, 2003",NaN,NaN,"Apr 19, 1999","Jul 17, 2022",NaN,NaN,...,NaN,"Apr 17, 2013",NaN,NaN,"Oct 19, 2014",NaN,NaN,NaN,"Jun 05, 2022",NaN
38,Fiscal Year Ends,"Sep 23, 2022","Dec 30, 2022","Jun 29, 2022","Dec 30, 2022","Dec 30, 2022","Jan 30, 2023","Dec 30, 2022","Jun 29, 2022","Dec 30, 2022",...,"Jan 30, 2023","Jan 30, 2023","Dec 30, 2022",NaN,"Dec 30, 2022",NaN,"Dec 30, 2022",NaN,"Dec 30, 2022",NaN
39,Most Recent Quarter (mrq),"Dec 30, 2022","Dec 30, 2022","Dec 30, 2022","Dec 30, 2022","Dec 30, 2022","Jan 30, 2023","Dec 30, 2022","Dec 30, 2022","Dec 30, 2022",...,"Jan 30, 2023","Jan 30, 2023","Dec 30, 2022",NaN,"Dec 30, 2022",NaN,"Dec 30, 2022",NaN,"Dec 30, 2022",NaN
40,Profit Margin,24.56%,-0.53%,33.05%,-31.07%,-75.70%,1.91%,21.20%,-90.31%,38.78%,...,2.36%,0.66%,-55.66%,NaN,25.33%,NaN,0.00%,NaN,0.00%,NaN
41,Operating Margin (ttm),29.41%,2.38%,40.97%,-26.21%,-73.12%,4.01%,26.46%,-40.13%,47.54%,...,5.59%,5.93%,-40.83%,NaN,44.12%,NaN,0.00%,NaN,106.71%,NaN
42,Return on Assets (ttm),19.57%,1.73%,14.83%,-9.69%,-4.77%,6.28%,12.91%,-17.43%,20.75%,...,1.96%,1.20%,-19.44%,NaN,2.72%,NaN,-16.48%,NaN,-5.95%,NaN
43,Return on Equity (ttm),147.94%,-1.92%,39.31%,-44.88%,-14.43%,12.84%,23.62%,-229.75%,32.76%,...,1.73%,0.36%,-79.14%,NaN,14.38%,NaN,-28.13%,NaN,-36.53%,NaN
44,Revenue (ttm),387.54B,513.98B,204.09B,4.6B,1.36B,611.29B,282.84B,3.05B,214.2M,...,4.39B,31.35B,1.01B,NaN,3.77B,NaN,NaN,NaN,-377.6M,NaN
45,Revenue Per Share (ttm),24.08,50.44,27.33,2.86,1.55,224.41,21.65,9.03,2.07,...,14.81,31.60,5.53,NaN,8.04,NaN,NaN,NaN,-11.05,NaN
46,Quarterly Revenue Growth (yoy),-5.50%,8.60%,2.00%,0.10%,4.70%,7.30%,1.00%,-30.10%,58.60%,...,4.30%,14.40%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,Gross Profit (ttm),170.78B,225.15B,135.62B,2.81B,906M,147.57B,156.63B,698.3M,160.02M,...,3.29B,22.99B,-41.1M,NaN,3.77B,NaN,NaN,NaN,-377.6M,NaN
48,EBITDA,125.29B,54.17B,97.95B,-1B,NaN,35.47B,90.77B,-1.11B,103.08M,...,327.75M,5.44B,-375.13M,NaN,NaN,NaN,-392.34M,NaN,NaN,NaN
49,Net Income Avi to Common (ttm),95.17B,-2.72B,67.45B,-1.43B,-1.03B,11.68B,59.97B,-2.76B,83.08M,...,103.7M,208M,-424.6M,NaN,864.79M,NaN,-411.91M,NaN,-416.96M,NaN
50,Diluted EPS (ttm),5.90,-0.28,9.00,-0.84,-1.20,4.27,4.64,-8.52,0.75,...,0.33,0.21,-2.4600,NaN,1.80,NaN,-0.86,NaN,-12.21,NaN
51,Quarterly Earnings Growth (yoy),-13.40%,-98.10%,-12.50%,NaN,NaN,76.20%,-34.00%,NaN,173.60%,...,NaN,NaN,NaN,NaN,-43.10%,NaN,NaN,NaN,NaN,NaN
52,Total Cash (mrq),51.36B,70.03B,99.5B,3.94B,9.86B,8.63B,113.76B,871M,298.4M,...,5.41B,12.51B,337.09M,NaN,1.39B,NaN,1.06B,NaN,176.2M,NaN
53,Total Cash Per Share (mrq),3.25,6.83,13.37,2.49,11,3.2,8.88,2.52,2.82,...,18.42,12.51,1.61,NaN,2.93,NaN,2.41,NaN,4.55,NaN
54,Total Debt (mrq),111.11B,169.94B,77.98B,4.18B,1.98B,61.03B,29.98B,2.42B,3.89M,...,96.48M,14.88B,442.8M,NaN,22.02B,NaN,105.42M,NaN,4.24B,NaN
55,Total Debt/Equity (mrq),195.87,116.36,42.58,161.79,28.49,72.67,11.70,7928.85,1.30,...,1.55,25.50,109.79,NaN,314.13,NaN,7.99,NaN,526.93,NaN
56,Current Ratio (mrq),0.94,0.94,1.93,4.32,1.35,0.82,2.38,2.28,5.57,...,3.66,1.02,1.00,NaN,1.40,NaN,22.91,NaN,0.07,NaN
57,Book Value Per Share (mrq),3.58,14.26,24.59,1.64,7.79,28.48,19.93,0.09,2.85,...,21.12,59.49,1.97,NaN,12.00,NaN,3.01,NaN,13.06,NaN
58,Operating Cash Flow (ttm),109.19B,46.75B,84.39B,184.61M,-852M,28.84B,91.49B,-1.3B,116.05M,...,1.29B,7.11B,-316.7M,NaN,6.87B,NaN,-218.02M,NaN,196.08M,NaN
59,Levered Free Cash Flow (ttm),84.73B,7.62M,44.61B,913.45M,NaN,12.37B,52.53B,-301.74M,89.7M,...,1.64B,10.22B,-115.17M,NaN,NaN,NaN,-242.25M,NaN,NaN,NaN

Some additional information about our dataframe stock_info:

In [ ]:
stock_info.info()          # Ottieni informazioni sulle colonne e sui tipi di dati

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Columns: 101 entries, 0 to VYM
dtypes: float64(11), object(90)
memory usage: 47.5+ KB

In [ ]:
stock_info.shape           # Ottieni le dimensioni del dataframe (righe, colonne)

(60, 101)

Thanks to these codes, we can state that some indexes are not required. We proceed with the elimination of these unnecessary indexes through the Data Cleaning process

##Data Cleaning

#### Stocks dataset cleaning

In [ ]:
#we drop the NaN thanks to the .fillna(0) code
df_stock = stocks.fillna(0)
print(df_stock)

       Unnamed: 0.7  Unnamed: 0.6  Unnamed: 0.5  Unnamed: 0.4  Unnamed: 0.3  \
0                 0           0.0           0.0           0.0           0.0
1                 1           1.0           1.0           1.0           1.0
2                 2           2.0           2.0           2.0           2.0
3                 3           3.0           3.0           3.0           3.0
4                 4           4.0           4.0           4.0           4.0
...             ...           ...           ...           ...           ...
24844           246           0.0           0.0           0.0           0.0
24845           247           0.0           0.0           0.0           0.0
24846           248           0.0           0.0           0.0           0.0
24847           249           0.0           0.0           0.0           0.0
24848           250           0.0           0.0           0.0           0.0

       Unnamed: 0.2  Unnamed: 0.1  Unnamed: 0 Stock Name                 Date  \
0               0.0           0.0         0.0       AAPL  2022-01-10 05:00:00
1               1.0           1.0         1.0       AAPL  2022-01-11 05:00:00
2               2.0           2.0         2.0       AAPL  2022-01-12 05:00:00
3               3.0           3.0         3.0       AAPL  2022-01-13 05:00:00
4               4.0           4.0         4.0       AAPL  2022-01-14 05:00:00
...             ...           ...         ...        ...                  ...
24844           0.0           0.0         0.0        VYM  2023-01-03 05:00:00
24845           0.0           0.0         0.0        VYM  2023-01-04 05:00:00
24846           0.0           0.0         0.0        VYM  2023-01-05 05:00:00
24847           0.0           0.0         0.0        VYM  2023-01-06 05:00:00
24848           0.0           0.0         0.0        VYM  2023-01-09 05:00:00

           Open   Close      High       Low       Volume
0      169.0800  172.19  172.5000  168.1700  106754551.0
1      172.3200  175.08  175.1800  170.8200   76138312.0
2      176.1200  175.53  177.1800  174.8200   74805173.0
3      175.7800  172.19  176.6200  171.7900   84405760.0
4      171.3400  173.07  173.7800  171.0900   80440778.0
...         ...     ...       ...       ...          ...
24844  108.5200  108.02  108.8000  107.2000    2377721.0
24845  108.3200  108.94  109.5000  108.0300    7427816.0
24846  108.4881  108.39  108.7500  107.8209    1829917.0
24847  109.2900  110.77  111.0500  109.0900    1624080.0
24848  111.1400  109.82  111.3791  109.7600    2572711.0

[24849 rows x 15 columns]

In [ ]:
#then we lose the "Unnamed" row with .drop code
datafr_stock = df_stock.drop(['Unnamed: 0', 'Unnamed: 0.1', 'Unnamed: 0.2', 'Unnamed: 0.3', 'Unnamed: 0.4', 'Unnamed: 0.5', 'Unnamed: 0.6', 'Unnamed: 0.7' ], axis=1)
print(datafr_stock)

      Stock Name                 Date      Open   Close      High       Low  \
0           AAPL  2022-01-10 05:00:00  169.0800  172.19  172.5000  168.1700
1           AAPL  2022-01-11 05:00:00  172.3200  175.08  175.1800  170.8200
2           AAPL  2022-01-12 05:00:00  176.1200  175.53  177.1800  174.8200
3           AAPL  2022-01-13 05:00:00  175.7800  172.19  176.6200  171.7900
4           AAPL  2022-01-14 05:00:00  171.3400  173.07  173.7800  171.0900
...          ...                  ...       ...     ...       ...       ...
24844        VYM  2023-01-03 05:00:00  108.5200  108.02  108.8000  107.2000
24845        VYM  2023-01-04 05:00:00  108.3200  108.94  109.5000  108.0300
24846        VYM  2023-01-05 05:00:00  108.4881  108.39  108.7500  107.8209
24847        VYM  2023-01-06 05:00:00  109.2900  110.77  111.0500  109.0900
24848        VYM  2023-01-09 05:00:00  111.1400  109.82  111.3791  109.7600

            Volume
0      106754551.0
1       76138312.0
2       74805173.0
3       84405760.0
4       80440778.0
...            ...
24844    2377721.0
24845    7427816.0
24846    1829917.0
24847    1624080.0
24848    2572711.0

[24849 rows x 7 columns]

#### stock_info dataset cleaning

In [ ]:
#again, we drop the NaN thanks to the .fillna(0) code
si_cleaned = stock_info.fillna(0)
print(si_cleaned)

                                                 0          AAPL  \
0                            Market Cap (intraday)         2.61T
1                                 Enterprise Value         2.66T
2                                     Trailing P/E         27.96
3                                      Forward P/E         27.86
4                        PEG Ratio (5 yr expected)          2.78
5                                Price/Sales (ttm)          6.88
6                                 Price/Book (mrq)         45.93
7                         Enterprise Value/Revenue          6.88
8                          Enterprise Value/EBITDA         20.81
9                                Beta (5Y Monthly)          1.30
10                                52-Week Change 3        -5.63%
11                         S&P500 52-Week Change 3        -7.59%
12                                  52 Week High 3        176.15
13                                   52 Week Low 3        124.17
14                         50-Day Moving Average 3        154.06
15                        200-Day Moving Average 3        149.38
16                             Avg Vol (3 month) 3        65.35M
17                              Avg Vol (10 day) 3         51.1M
18                            Shares Outstanding 5        15.82B
19                    Implied Shares Outstanding 6             0
20                                         Float 8        15.81B
21                            % Held by Insiders 1         0.07%
22                        % Held by Institutions 1        61.28%
23                   Shares Short (Mar 14, 2023) 4       107.42M
24                    Short Ratio (Mar 14, 2023) 4          1.75
25               Short % of Float (Mar 14, 2023) 4         0.68%
26  Short % of Shares Outstanding (Mar 14, 2023) 4         0.68%
27       Shares Short (prior month Feb 14, 2023) 4       104.34M
28                  Forward Annual Dividend Rate 4          0.92
29                 Forward Annual Dividend Yield 4         0.57%
30                 Trailing Annual Dividend Rate 3          0.91
31                Trailing Annual Dividend Yield 3         0.57%
32                 5 Year Average Dividend Yield 4          0.94
33                                  Payout Ratio 4        15.45%
34                                 Dividend Date 3  Feb 15, 2023
35                              Ex-Dividend Date 4  Feb 09, 2023
36                             Last Split Factor 2           4:1
37                               Last Split Date 3  Aug 30, 2020
38                                Fiscal Year Ends  Sep 23, 2022
39                       Most Recent Quarter (mrq)  Dec 30, 2022
40                                   Profit Margin        24.56%
41                          Operating Margin (ttm)        29.41%
42                          Return on Assets (ttm)        19.57%
43                          Return on Equity (ttm)       147.94%
44                                   Revenue (ttm)       387.54B
45                         Revenue Per Share (ttm)         24.08
46                  Quarterly Revenue Growth (yoy)        -5.50%
47                              Gross Profit (ttm)       170.78B
48                                          EBITDA       125.29B
49                  Net Income Avi to Common (ttm)        95.17B
50                               Diluted EPS (ttm)          5.90
51                 Quarterly Earnings Growth (yoy)       -13.40%
52                                Total Cash (mrq)        51.36B
53                      Total Cash Per Share (mrq)          3.25
54                                Total Debt (mrq)       111.11B
55                         Total Debt/Equity (mrq)        195.87
56                             Current Ratio (mrq)          0.94
57                      Book Value Per Share (mrq)          3.58
58                       Operating Cash Flow (ttm)       109.19B
59                    Levered Free Cash Flow (ttm)        84.73B

            AMZN          MSFT          SNAP          HOOD           WMT  \
0          1.05T         2.17T        16.70B         8.97B       406.50B
1          1.12T         2.13T        16.94B        -4.48B       456.80B
2              0         32.40             0             0         35.32
3          63.69         26.95             0             0         24.75
4           2.30          2.19             0             0          4.21
5           2.02         10.71          3.69          6.48          0.67
6           7.16         11.85          6.47          1.29          5.30
7           2.17         10.44          3.68         -3.30          0.75
8          29.10         21.58        -14.39          5.09         15.18
9           1.25          0.92          1.20             0          0.49
10       -35.76%        -1.67%       -69.55%       -16.23%        -4.55%
11        -7.59%        -7.59%        -7.59%        -7.59%        -7.59%
12        158.65        294.18         35.39         12.76        160.77
13         81.43        213.43          7.33          6.81        117.27
14         98.42        265.65         10.83          9.74        142.86
15        107.33        254.31         10.76          9.63        138.62
16        64.92M        31.87M         33.4M         7.33M         6.72M
17        47.52M        25.77M        22.46M         7.47M         6.78M
18        10.25B         7.44B         1.33B       768.37M          2.7B
19             0             0             0       896.05M             0
20         9.24B         7.44B       969.04M       520.15M         1.42B
21         9.75%         0.06%         9.39%         8.06%        48.00%
22        60.46%        73.65%        52.92%        70.82%        32.88%
23        56.47M        35.91M        54.67M        35.22M         9.96M
24          1.01           1.3          1.72          5.31          1.36
25         0.63%         0.48%         6.60%         6.07%         0.72%
26         0.55%         0.48%         3.46%         3.93%         0.37%
27        62.13M        36.52M        54.29M        36.33M        12.53M
28             0          2.72             0             0          2.28
29             0         0.94%             0             0         1.51%
30          0.00          2.60          0.00          0.00          2.24
31         0.00%         0.92%         0.00%         0.00%         1.49%
32             0          1.12             0             0          1.77
33         0.00%        28.22%         0.00%         0.00%        52.46%
34             0  Jun 07, 2023             0             0  Jan 01, 2024
35             0  May 16, 2023             0             0  May 03, 2023
36          20:1           2:1             0             0           2:1
37  Jun 05, 2022  Feb 17, 2003             0             0  Apr 19, 1999
38  Dec 30, 2022  Jun 29, 2022  Dec 30, 2022  Dec 30, 2022  Jan 30, 2023
39  Dec 30, 2022  Dec 30, 2022  Dec 30, 2022  Dec 30, 2022  Jan 30, 2023
40        -0.53%        33.05%       -31.07%       -75.70%         1.91%
41         2.38%        40.97%       -26.21%       -73.12%         4.01%
42         1.73%        14.83%        -9.69%        -4.77%         6.28%
43        -1.92%        39.31%       -44.88%       -14.43%        12.84%
44       513.98B       204.09B          4.6B         1.36B       611.29B
45         50.44         27.33          2.86          1.55        224.41
46         8.60%         2.00%         0.10%         4.70%         7.30%
47       225.15B       135.62B         2.81B          906M       147.57B
48        54.17B        97.95B           -1B             0        35.47B
49        -2.72B        67.45B        -1.43B        -1.03B        11.68B
50         -0.28          9.00         -0.84         -1.20          4.27
51       -98.10%       -12.50%             0             0        76.20%
52        70.03B         99.5B         3.94B         9.86B         8.63B
53          6.83         13.37          2.49            11           3.2
54       169.94B        77.98B         4.18B         1.98B        61.03B
55        116.36         42.58        161.79         28.49         72.67
56          0.94          1.93          4.32          1.35          0.82
57         14.26         24.59          1.64          7.79         28.48
58        46.75B        84.39B       184.61M         -852M        28.84B
59         7.62M        44.61B       913.45M             0        12.37B

            GOOG          PTON          CPRX  ...            ZM           CRM  \
0          1.37T         3.95B         1.84B  ...        21.11B       192.55B
1          1.28T         5.49B         1.54B  ...        15.80B       194.13B
2          23.45             0         23.17  ...        211.32        916.90
3          19.80             0         11.59  ...         17.33         27.03
4           1.17             0             0  ...          2.69          1.35
5           4.98          1.26          9.04  ...          4.98          6.12
6           5.35        129.45          6.11  ...          3.40          3.30
7           4.53          1.80          7.20  ...          3.60          6.19
8          14.63         -2.17         14.96  ...         48.20         34.40
9           1.09          1.95          1.16  ...         -0.22          1.21
10       -18.55%       -54.10%       104.78%  ...       -39.07%        -3.49%
11        -7.59%        -7.59%        -7.59%  ...        -7.59%        -7.59%
12        131.92         26.50         22.11  ...        124.05        200.00
13         83.45          6.66          6.15  ...         63.55        126.34
14         98.82         12.48         15.79  ...         73.00        179.13
15        101.76         10.60         14.44  ...         81.76        162.77
16         32.5M        12.48M         2.26M  ...         3.89M         8.56M
17        24.03M         6.88M         1.68M  ...         2.82M          5.7M
18         5.97B       327.13M       105.65M  ...       247.17M            1B
19             0             0             0  ...             0             0
20        11.07B        304.3M        93.47M  ...        223.5M       968.26M
21         0.02%         2.28%         5.97%  ...         9.34%         3.25%
22        63.30%        88.86%        82.78%  ...        66.17%        78.15%
23        33.46M           36M         9.78M  ...        12.01M        10.74M
24          1.12          3.85          5.81  ...          2.57           1.1
25             0        12.49%         9.99%  ...         4.87%         1.11%
26         0.26%        10.40%         9.26%  ...         4.09%         1.07%
27        28.55M        37.82M         9.74M  ...        14.93M        11.02M
28             0             0             0  ...             0             0
29             0             0             0  ...             0             0
30          0.00          0.00          0.00  ...          0.00          0.00
31         0.00%         0.00%         0.00%  ...         0.00%         0.00%
32             0             0             0  ...             0             0
33         0.00%         0.00%         0.00%  ...         0.00%         0.00%
34             0             0             0  ...             0             0
35             0             0             0  ...             0             0
36          20:1             0             0  ...             0           4:1
37  Jul 17, 2022             0             0  ...             0  Apr 17, 2013
38  Dec 30, 2022  Jun 29, 2022  Dec 30, 2022  ...  Jan 30, 2023  Jan 30, 2023
39  Dec 30, 2022  Dec 30, 2022  Dec 30, 2022  ...  Jan 30, 2023  Jan 30, 2023
40        21.20%       -90.31%        38.78%  ...         2.36%         0.66%
41        26.46%       -40.13%        47.54%  ...         5.59%         5.93%
42        12.91%       -17.43%        20.75%  ...         1.96%         1.20%
43        23.62%      -229.75%        32.76%  ...         1.73%         0.36%
44       282.84B         3.05B        214.2M  ...         4.39B        31.35B
45         21.65          9.03          2.07  ...         14.81         31.60
46         1.00%       -30.10%        58.60%  ...         4.30%        14.40%
47       156.63B        698.3M       160.02M  ...         3.29B        22.99B
48        90.77B        -1.11B       103.08M  ...       327.75M         5.44B
49        59.97B        -2.76B        83.08M  ...        103.7M          208M
50          4.64         -8.52          0.75  ...          0.33          0.21
51       -34.00%             0       173.60%  ...             0             0
52       113.76B          871M        298.4M  ...         5.41B        12.51B
53          8.88          2.52          2.82  ...         18.42         12.51
54        29.98B         2.42B         3.89M  ...        96.48M        14.88B
55         11.70       7928.85          1.30  ...          1.55         25.50
56          2.38          2.28          5.57  ...          3.66          1.02
57         19.93          0.09          2.85  ...         21.12         59.49
58        91.49B         -1.3B       116.05M  ...         1.29B         7.11B
59        52.53B      -301.74M         89.7M  ...         1.64B        10.22B

            FUBO  BND          RITM  SPHD            QS   VEA           IVR  \
0        230.66M  0.0         3.70B  0.00         3.21B  0.00       446.26M
1        336.37M  0.0             0  0.00         2.25B  0.00             0
2              0  0.0          4.33  0.00             0  0.00          1.10
3              0  0.0          5.61  0.00             0  0.00          1.99
4              0  0.0             0  0.00             0  0.00             0
5           0.20  0.0          1.06  0.00             0  0.00          0.87
6           0.56  0.0          0.65  0.00          2.43  0.00          0.88
7           0.33  0.0             0  0.00             0  0.00             0
8          -0.90  0.0             0  0.00         -6.03  0.00             0
9           2.45  1.0          1.78  0.74          5.27  1.09          1.55
10       -78.46%  0.0       -24.79%  0.00       -58.17%  0.00       -47.61%
11        -7.59%  0.0        -7.59%  0.00        -7.59%  0.00        -7.59%
12        8.1400  0.0         11.75  0.00         18.87  0.00         20.00
13        0.9600  0.0          6.86  0.00          5.11  0.00          9.60
14        1.7604  0.0          8.67  0.00          8.41  0.00         12.30
15        2.7996  0.0          8.88  0.00          8.74  0.00         13.50
16        13.46M  0.0         4.68M  0.00         6.06M  0.00       970.04k
17        12.51M  0.0         4.23M  0.00         3.65M  0.00         1.27M
18        209.7M  0.0       473.73M  0.00       360.52M  0.00        41.47M
19             0  0.0             0  0.00             0  0.00             0
20       203.97M  0.0       470.94M  0.00       276.96M  0.00        38.62M
21         4.34%  0.0         0.68%  0.00        26.03%  0.00         0.21%
22        41.49%  0.0        48.36%  0.00        39.93%  0.00        47.35%
23        39.24M  0.0         4.77M  0.00        52.32M  0.00         3.69M
24          2.92  0.0          1.11  0.00          7.75  0.00          2.98
25        19.49%  0.0         1.01%  0.00        19.50%  0.00        11.81%
26        18.71%  0.0         1.01%  0.00        11.89%  0.00         8.89%
27        51.68M  0.0        14.78M  0.00        60.47M  0.00          3.9M
28             0  0.0             1  0.00             0  0.00           1.6
29             0  0.0        12.82%  0.00             0  0.00        14.87%
30          0.00  0.0          1.00  0.00          0.00  0.00          3.10
31         0.00%  0.0        12.63%  0.00         0.00%  0.00        30.04%
32             0  0.0         11.51  0.00             0  0.00         20.18
33         0.00%  0.0        55.56%  0.00         0.00%  0.00             0
34  Feb 27, 2019  0.0  Apr 27, 2023  0.00             0  0.00  Apr 26, 2023
35             0  0.0  Mar 29, 2023  0.00             0  0.00  Apr 05, 2023
36             0  0.0           1:2  0.00             0  0.00          1:10
37             0  0.0  Oct 19, 2014  0.00             0  0.00  Jun 05, 2022
38  Dec 30, 2022  0.0  Dec 30, 2022  0.00  Dec 30, 2022  0.00  Dec 30, 2022
39  Dec 30, 2022  0.0  Dec 30, 2022  0.00  Dec 30, 2022  0.00  Dec 30, 2022
40       -55.66%  0.0        25.33%  0.00         0.00%  0.00         0.00%
41       -40.83%  0.0        44.12%  0.00         0.00%  0.00       106.71%
42       -19.44%  0.0         2.72%  0.00       -16.48%  0.00        -5.95%
43       -79.14%  0.0        14.38%  0.00       -28.13%  0.00       -36.53%
44         1.01B  0.0         3.77B  0.00             0  0.00       -377.6M
45          5.53  0.0          8.04  0.00             0  0.00        -11.05
46             0  0.0             0  0.00             0  0.00             0
47        -41.1M  0.0         3.77B  0.00             0  0.00       -377.6M
48      -375.13M  0.0             0  0.00      -392.34M  0.00             0
49       -424.6M  0.0       864.79M  0.00      -411.91M  0.00      -416.96M
50       -2.4600  0.0          1.80  0.00         -0.86  0.00        -12.21
51             0  0.0       -43.10%  0.00             0  0.00             0
52       337.09M  0.0         1.39B  0.00         1.06B  0.00        176.2M
53          1.61  0.0          2.93  0.00          2.41  0.00          4.55
54        442.8M  0.0        22.02B  0.00       105.42M  0.00         4.24B
55        109.79  0.0        314.13  0.00          7.99  0.00        526.93
56          1.00  0.0          1.40  0.00         22.91  0.00          0.07
57          1.97  0.0         12.00  0.00          3.01  0.00         13.06
58       -316.7M  0.0         6.87B  0.00      -218.02M  0.00       196.08M
59      -115.17M  0.0             0  0.00      -242.25M  0.00             0

     VYM
0   0.00
1   0.00
2   0.00
3   0.00
4   0.00
5   0.00
6   0.00
7   0.00
8   0.00
9   0.77
10  0.00
11  0.00
12  0.00
13  0.00
14  0.00
15  0.00
16  0.00
17  0.00
18  0.00
19  0.00
20  0.00
21  0.00
22  0.00
23  0.00
24  0.00
25  0.00
26  0.00
27  0.00
28  0.00
29  0.00
30  0.00
31  0.00
32  0.00
33  0.00
34  0.00
35  0.00
36  0.00
37  0.00
38  0.00
39  0.00
40  0.00
41  0.00
42  0.00
43  0.00
44  0.00
45  0.00
46  0.00
47  0.00
48  0.00
49  0.00
50  0.00
51  0.00
52  0.00
53  0.00
54  0.00
55  0.00
56  0.00
57  0.00
58  0.00
59  0.00

[60 rows x 101 columns]


In order to have a cleaner view of the stock_info dataset, we transpose the columns with rows, and vice versa

In [ ]:
#we utilized the .transpose() code to exhange rows and columns
stock_info_T=si_cleaned.transpose()
stock_info_T

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
0,Market Cap (intraday),Enterprise Value,Trailing P/E,Forward P/E,PEG Ratio (5 yr expected),Price/Sales (ttm),Price/Book (mrq),Enterprise Value/Revenue,Enterprise Value/EBITDA,Beta (5Y Monthly),...,Diluted EPS (ttm),Quarterly Earnings Growth (yoy),Total Cash (mrq),Total Cash Per Share (mrq),Total Debt (mrq),Total Debt/Equity (mrq),Current Ratio (mrq),Book Value Per Share (mrq),Operating Cash Flow (ttm),Levered Free Cash Flow (ttm)
AAPL,2.61T,2.66T,27.96,27.86,2.78,6.88,45.93,6.88,20.81,1.30,...,5.90,-13.40%,51.36B,3.25,111.11B,195.87,0.94,3.58,109.19B,84.73B
AMZN,1.05T,1.12T,0,63.69,2.30,2.02,7.16,2.17,29.10,1.25,...,-0.28,-98.10%,70.03B,6.83,169.94B,116.36,0.94,14.26,46.75B,7.62M
MSFT,2.17T,2.13T,32.40,26.95,2.19,10.71,11.85,10.44,21.58,0.92,...,9.00,-12.50%,99.5B,13.37,77.98B,42.58,1.93,24.59,84.39B,44.61B
SNAP,16.70B,16.94B,0,0,0,3.69,6.47,3.68,-14.39,1.20,...,-0.84,0,3.94B,2.49,4.18B,161.79,4.32,1.64,184.61M,913.45M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SPHD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.74,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
QS,3.21B,2.25B,0,0,0,0,2.43,0,-6.03,5.27,...,-0.86,0,1.06B,2.41,105.42M,7.99,22.91,3.01,-218.02M,-242.25M
VEA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.09,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
IVR,446.26M,0,1.10,1.99,0,0.87,0.88,0,0,1.55,...,-12.21,0,176.2M,4.55,4.24B,526.93,0.07,13.06,196.08M,0
VYM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.77,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

##Dataset Creation

Now we build the dataframes required to answer our questions, taking into consideration only those columns that we will analyze.

We keep data about company's evaluations which are:

For the first question:

1. **Company**: The name or code of the companies to uniquely identify them.

2. **ROE**: The Return on Equity (ROE) of companies, which represents the profitability for shareholders.

3. **Market Cap**: The market capitalization of companies, which is the total market value of a company's shares.

4. **Current Ratio**: The current ratio of companies, which measures the ability of a company to cover its short-term obligations with its current assets.

In [ ]:
#to list the first 100 rows of the dataset we used the head() method
stocks_100 = stock_info_T.head(100)
stocks_100

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
0,Market Cap (intraday),Enterprise Value,Trailing P/E,Forward P/E,PEG Ratio (5 yr expected),Price/Sales (ttm),Price/Book (mrq),Enterprise Value/Revenue,Enterprise Value/EBITDA,Beta (5Y Monthly),...,Diluted EPS (ttm),Quarterly Earnings Growth (yoy),Total Cash (mrq),Total Cash Per Share (mrq),Total Debt (mrq),Total Debt/Equity (mrq),Current Ratio (mrq),Book Value Per Share (mrq),Operating Cash Flow (ttm),Levered Free Cash Flow (ttm)
AAPL,2.61T,2.66T,27.96,27.86,2.78,6.88,45.93,6.88,20.81,1.30,...,5.90,-13.40%,51.36B,3.25,111.11B,195.87,0.94,3.58,109.19B,84.73B
AMZN,1.05T,1.12T,0,63.69,2.30,2.02,7.16,2.17,29.10,1.25,...,-0.28,-98.10%,70.03B,6.83,169.94B,116.36,0.94,14.26,46.75B,7.62M
MSFT,2.17T,2.13T,32.40,26.95,2.19,10.71,11.85,10.44,21.58,0.92,...,9.00,-12.50%,99.5B,13.37,77.98B,42.58,1.93,24.59,84.39B,44.61B
SNAP,16.70B,16.94B,0,0,0,3.69,6.47,3.68,-14.39,1.20,...,-0.84,0,3.94B,2.49,4.18B,161.79,4.32,1.64,184.61M,913.45M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
RITM,3.70B,0,4.33,5.61,0,1.06,0.65,0,0,1.78,...,1.80,-43.10%,1.39B,2.93,22.02B,314.13,1.40,12.00,6.87B,0
SPHD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.74,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
QS,3.21B,2.25B,0,0,0,0,2.43,0,-6.03,5.27,...,-0.86,0,1.06B,2.41,105.42M,7.99,22.91,3.01,-218.02M,-242.25M
VEA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.09,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
IVR,446.26M,0,1.10,1.99,0,0.87,0.88,0,0,1.55,...,-12.21,0,176.2M,4.55,4.24B,526.93,0.07,13.06,196.08M,0

Now that the first 100 stocks are listed in the stocks_100 dataset, we gather together the ROE, Current Ratio, and Market Cap

But we do not know how exactly is called the ROE column, so we sort it out with the .columns function

In [ ]:
# here we obtain the columns' names as a list
columns_names = stocks_100.columns.tolist()

In [ ]:
ROE_stocks_100 = stock_info_T.iloc[:, 44]
ROE_stocks_100

0       Revenue (ttm)
AAPL          387.54B
AMZN          513.98B
MSFT          204.09B
SNAP             4.6B
            ...
SPHD              0.0
QS                  0
VEA               0.0
IVR           -377.6M
VYM               0.0
Name: 44, Length: 101, dtype: object

In [ ]:
# Cerca il nome di colonna desiderato
column_name = 'Return on Equity'

if column_name in columns_names:
    print("The column name is present in the dataframe.")
else:
    print("The column name is not present in the dataframe.")

The column name is not present in the dataframe.

In [ ]:
# Average ROE of 21.17%
#average_roe = 21.1

In [ ]:
#we filter the companies with a ROE higher than the average
#better_companies = stock_info_T[stock_info_T['Return on Equity (ttm)'] > average_roe]

In [ ]:
# First 100 firms according to their ROE
#top_100_companies = stock_info_T.nlargest(100, 'ROE')

In [ ]:
# Now we look for companies with a ROE superior than the first 100 businesses
#better_than_top_100 = better_companies[better_companies['ROE'].isin(top_100_companies['ROE'])]

In [ ]:
#results
print("Businesses that perform better than the first 100 companies according to ROE:")
print(better_than_top_100)

Businesses that perform better than the first 100 companies according to ROE:

NameError: ignored

#KDD ANALYSIS

You are required to perform unsupervised learning techniques on 100
stocks. You will have access to daily open, high, low, and close (OHLC) values for
each stock, as well as other financial indexes and economic information (e.g.
https://finance.yahoo.com/quote/GE/key-statistics?p=GE). In this part, you have the
freedom to choose the type and goals of the analysis. You can use all or part of the
data, and even search for additional data to support your analysis. You are expected
to conduct an initial exploratory analysis of the dataset and its features, and possibly
apply feature selection/dimensionality reduction algorithms. Additionally, you should
try out different clustering algorithms (at least the two covered in class). Each choice
should be adequately justified.

In [ ]:
import numpy as np
pivot= stock_data.pivot()

#Predictive Task

In this case, the focus will be on a reduced version of the dataset,
which includes 20 stock indices with daily OHLC values collected between
30-09-2021 and 30-09-2022. The goal is to predict whether tomorrow's closing value
will be higher or lower than today's closing value, using the stock trend of the past as
input to the algorithm (e.g. the input could be a 10-dimensional vector composed by
the last 10 closing values, and the output a binary prediction, higher or lower).
Additionally, to enhance the performance of your algorithm, you can utilize past
tweets related to the specific stock index. During the presentation, you should
thoroughly explain each step you took to improve the performance of your model,
including feature engineering, feature transformation/selection, use of different
models, cross-validation, etc